// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA615tb0YowslsMOyBUjG2qHIengGEI464',
    appId: '1:307087474070:web:fa0a1691e6e76f7624f1b7',
    messagingSenderId: '307087474070',
    projectId: 'hm-putra',
    authDomain: 'hm-putra.firebaseapp.com',
    storageBucket: 'hm-putra.firebasestorage.app',
    measurementId: 'G-34JKC2DVGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpI_QlbMf-Nt0QVAvX2bzpj9Q-bvf2rVc',
    appId: '1:307087474070:android:6bb1a9bd16d2aeeb24f1b7',
    messagingSenderId: '307087474070',
    projectId: 'hm-putra',
    storageBucket: 'hm-putra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcs_axfB3vEMeqV7sf0dNLrJWv3A6K2bk',
    appId: '1:307087474070:ios:f4cd1ba1a817568924f1b7',
    messagingSenderId: '307087474070',
    projectId: 'hm-putra',
    storageBucket: 'hm-putra.firebasestorage.app',
    iosBundleId: 'com.example.firstAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcs_axfB3vEMeqV7sf0dNLrJWv3A6K2bk',
    appId: '1:307087474070:ios:f4cd1ba1a817568924f1b7',
    messagingSenderId: '307087474070',
    projectId: 'hm-putra',
    storageBucket: 'hm-putra.firebasestorage.app',
    iosBundleId: 'com.example.firstAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA615tb0YowslsMOyBUjG2qHIengGEI464',
    appId: '1:307087474070:web:bcf2ee36f60a763b24f1b7',
    messagingSenderId: '307087474070',
    projectId: 'hm-putra',
    authDomain: 'hm-putra.firebaseapp.com',
    storageBucket: 'hm-putra.firebasestorage.app',
    measurementId: 'G-BM96SEK5KH',
  );

}